# This is a sample Python script.
import twoSum
import lengthOfLongestSubstring
import findMedianSortedArrays
import longestPalindrome
import reverseInteger
# Press Double ⇧ to search everywhere for classes, files, tool windows, actions, and settings.


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print(twoSum.twoSum([3,2,4],6))
    print(lengthOfLongestSubstring.lengthOfLongestSubstring("abcabcbb"))
    print(findMedianSortedArrays.findMedianSortedArrays([2,3,4,5,6],[2,3,6,7,9]))
    #print(longestPalindrome.longestPalindrome("abababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababababa"))
    print(reverseInteger.reverse(-383))

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
